[package]
name = "geyser"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
agave-geyser-plugin-interface = "2.0.15"
solana-program = "2.0.15"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
